### PR TITLE
properly set auth token and no_ready_check for heroku redistogo

### PR DESCRIPTION
**Pull request by 100ideas**
https://github.com/hubot-scripts/hubot-redis-brain/issues/3

not sure if `no_ready_check: true` is really necessary - thoughts?

### CODE REVIEW

**Comment by technicalpickles** [comment]
> not sure if no_ready_check: true is really necessary - thoughts?

I'm not familiar with it. Is that something you needed to do for things to work, or just something you tend to use for the redis client?

**Comment by technicalpickles** [comment]
> not sure if no_ready_check: true is really necessary 

https://github.com/mranney/node_redis#connect for reference

**Comment by technicalpickles** [comment]
I'm looking a bit more closely, and I'm having a hard time determine what the change is that fixes passes the auth. The only functional change (ie not the logging changes) I see is using no_ready_check when auth is set.

**Comment by 100ideas** [comment]
It's cryptic because in this example the authentication details are stored in an environment variable, like

``` bash
REDISTOGO_URL=redis://redistogo:111111111111111111@sub.redistogo.com:10000
```

`Redis.createClient(info.port, info.hostname)` will throw an error if `REDISTOGO_URL` happens to contain authentication parameters unless (apparently?) it is also passed `{no_ready_check: true}`.

Adding the check let's me connect directly to a redistogo instance on heroku running along the free hubot web process.

Details: https://github.com/hubot-scripts/hubot-redis-brain/issues/4

**Comment by technicalpickles** [comment]
Sorry for the delay on this.

Since you've taken the time to help on  https://github.com/hubot-scripts/hubot-redis-brain/issues/3 and prepare a fix, I've added you as a collaborator. I'd suggest still using PRs, and following [semantic version](http://semver.org/). You can release with `grunt release:<patch|minor|major>`.

**Comment by technicalpickles** [comment]
Oh, and let me know your npm login (or create) one so I can add you there for releasing.

**Pull request merged**
